name: CI
on:
  push:
    branches: "*"
jobs:
  x86_64:
    runs-on: ubuntu-latest
    container:
      image: batoceralinux/batocera.linux-build:latest
    steps:
      - name: Build
        run: make O=/x86_64 BR2_EXTERNAL=/build -C /build/buildroot source
